// Generated by gencpp from file gap_finding/Gap.msg
// DO NOT EDIT!


#ifndef GAP_FINDING_MESSAGE_GAP_H
#define GAP_FINDING_MESSAGE_GAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gap_finding
{
template <class ContainerAllocator>
struct Gap_
{
  typedef Gap_<ContainerAllocator> Type;

  Gap_()
    : header()
    , leftRange(0.0)
    , leftAngle(0.0)
    , rightRange(0.0)
    , rightAngle(0.0)  {
    }
  Gap_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , leftRange(0.0)
    , leftAngle(0.0)
    , rightRange(0.0)
    , rightAngle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _leftRange_type;
  _leftRange_type leftRange;

   typedef float _leftAngle_type;
  _leftAngle_type leftAngle;

   typedef float _rightRange_type;
  _rightRange_type rightRange;

   typedef float _rightAngle_type;
  _rightAngle_type rightAngle;





  typedef boost::shared_ptr< ::gap_finding::Gap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gap_finding::Gap_<ContainerAllocator> const> ConstPtr;

}; // struct Gap_

typedef ::gap_finding::Gap_<std::allocator<void> > Gap;

typedef boost::shared_ptr< ::gap_finding::Gap > GapPtr;
typedef boost::shared_ptr< ::gap_finding::Gap const> GapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gap_finding::Gap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gap_finding::Gap_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gap_finding

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gap_finding': ['/home/nvidia/Desktop/f110_ws/src/algorithms/gap_finding/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gap_finding::Gap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gap_finding::Gap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gap_finding::Gap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gap_finding::Gap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gap_finding::Gap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gap_finding::Gap_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gap_finding::Gap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc7ab60870d0fcb9f6ec7084f4325f3a";
  }

  static const char* value(const ::gap_finding::Gap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc7ab60870d0fcb9ULL;
  static const uint64_t static_value2 = 0xf6ec7084f4325f3aULL;
};

template<class ContainerAllocator>
struct DataType< ::gap_finding::Gap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gap_finding/Gap";
  }

  static const char* value(const ::gap_finding::Gap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gap_finding::Gap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A gap computed from sensor_msgs/LaserScan message data\n\
\n\
Header header\n\
\n\
# A gap is represented by 4 numbers: the ranges and angles (measured by the lidar) of the laser rays striking the left and \n\
# right boundary of the gap\n\
float32 leftRange\n\
float32 leftAngle\n\
float32 rightRange\n\
float32 rightAngle\n\
\n\
# In the future it might be useful to also include the ranges in-between the left and right boundaries \n\
# in case that is used in the navigation algorithm.\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gap_finding::Gap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gap_finding::Gap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.leftRange);
      stream.next(m.leftAngle);
      stream.next(m.rightRange);
      stream.next(m.rightAngle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gap_finding::Gap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gap_finding::Gap_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "leftRange: ";
    Printer<float>::stream(s, indent + "  ", v.leftRange);
    s << indent << "leftAngle: ";
    Printer<float>::stream(s, indent + "  ", v.leftAngle);
    s << indent << "rightRange: ";
    Printer<float>::stream(s, indent + "  ", v.rightRange);
    s << indent << "rightAngle: ";
    Printer<float>::stream(s, indent + "  ", v.rightAngle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAP_FINDING_MESSAGE_GAP_H
