// Generated by gencpp from file gap_finding/gaps.msg
// DO NOT EDIT!


#ifndef GAP_FINDING_MESSAGE_GAPS_H
#define GAP_FINDING_MESSAGE_GAPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <gap_finding/Gap.h>

namespace gap_finding
{
template <class ContainerAllocator>
struct gaps_
{
  typedef gaps_<ContainerAllocator> Type;

  gaps_()
    : header()
    , gaps()  {
    }
  gaps_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gaps(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::gap_finding::Gap_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::gap_finding::Gap_<ContainerAllocator> >::other >  _gaps_type;
  _gaps_type gaps;





  typedef boost::shared_ptr< ::gap_finding::gaps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gap_finding::gaps_<ContainerAllocator> const> ConstPtr;

}; // struct gaps_

typedef ::gap_finding::gaps_<std::allocator<void> > gaps;

typedef boost::shared_ptr< ::gap_finding::gaps > gapsPtr;
typedef boost::shared_ptr< ::gap_finding::gaps const> gapsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gap_finding::gaps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gap_finding::gaps_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gap_finding

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gap_finding': ['/home/nvidia/Desktop/f110_ws/src/algorithms/gap_finding/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gap_finding::gaps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gap_finding::gaps_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gap_finding::gaps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gap_finding::gaps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gap_finding::gaps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gap_finding::gaps_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gap_finding::gaps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c433d339b96f265e8d4af6ca8e2dbd8";
  }

  static const char* value(const ::gap_finding::gaps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c433d339b96f265ULL;
  static const uint64_t static_value2 = 0xe8d4af6ca8e2dbd8ULL;
};

template<class ContainerAllocator>
struct DataType< ::gap_finding::gaps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gap_finding/gaps";
  }

  static const char* value(const ::gap_finding::gaps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gap_finding::gaps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Gap[] gaps\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: gap_finding/Gap\n\
# A gap computed from sensor_msgs/LaserScan message data\n\
\n\
Header header\n\
\n\
# A gap is represented by 4 numbers: the ranges and angles (measured by the lidar) of the laser rays striking the left and \n\
# right boundary of the gap\n\
float32 leftRange\n\
float32 leftAngle\n\
float32 rightRange\n\
float32 rightAngle\n\
\n\
# In the future it might be useful to also include the ranges in-between the left and right boundaries \n\
# in case that is used in the navigation algorithm.\n\
";
  }

  static const char* value(const ::gap_finding::gaps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gap_finding::gaps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gaps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gaps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gap_finding::gaps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gap_finding::gaps_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gaps[]" << std::endl;
    for (size_t i = 0; i < v.gaps.size(); ++i)
    {
      s << indent << "  gaps[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gap_finding::Gap_<ContainerAllocator> >::stream(s, indent + "    ", v.gaps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAP_FINDING_MESSAGE_GAPS_H
